workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      groups:
        - keystore_credentials # فراخوانی متغیرهای امضا
      flutter: 3.29.3
      java: 21

    scripts:
      - name: Set up keystore
        script: |
          # ساخت فایل release.jks از روی متغیر CM_KEYSTORE
          echo $CM_KEYSTORE | base64 --decode > /tmp/release.jks

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Release APK
        script: |
          flutter build apk --release --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*-release.apk
