workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: 3.29.3
      java: 21

    scripts:
      - name: Show versions
        script: |
          flutter --version
          dart --version

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Get SHA-1
        script: |
          cd android
          ./gradlew signingReport

      - name: Build APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
