name: safir_passengers
description: "Safir Taxi Passenger Application"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # پکیج‌های چندزبانگی
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter

  # پکیج‌های نقشه و Vector
  maplibre_gl: ^0.26.2
  latlong2: ^0.9.1

  # پکیج‌های GPS و اینترنت
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.4

  # فایربیس (سرویس‌های ابری)
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.2
  flutter_geofire: ^2.0.7
  google_sign_in: ^6.2.1

  # پکیج‌های کاربردی و ابزار سیستم
  permission_handler: ^11.3.1
  http: ^1.2.2
  provider: ^6.1.2
  restart_app: ^1.2.1
  url_launcher: ^6.3.0
  country_picker: ^2.0.24
  rounded_loading_button_plus: ^3.0.1
  cupertino_icons: ^1.0.6
  pinput: ^5.0.1
  flutter_polyline_points: ^2.1.0
  loading_animation_widget: ^1.2.1

  # پکیج‌های اضافه شده برای رفع خطای بیلد
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  image_picker: ^1.1.2

  # سیستم صوتی
  flutter_tts: ^4.0.2

  # پکیج‌های پرداخت
  flutter_stripe: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vehicles/
    - assets/lang/
    - assets/map/style.json
    - assets/fonts/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/iranyekanwebregular.ttf
          weight: 400
        - asset: assets/fonts/iranyekanwebbold.ttf
          weight: 700

dependency_overrides:
  vector_math: 2.1.4
